### ISSUE TITLE
Why UCY datasets need to convert the positions from image coordinnates to  world coordinates

### ISSUE THREAD

**Issue by sunyuan789** [Habiba-Amroune/ETH-UCY-Preprocessing#1]
Thanks for your code. It's useful. But I have some questions, could you help me? Why UCY datasets need to convert the positions from image coordinates to world coordinates?

**Comment by Habiba-Amroune** [comment]
Hello, this preprocessed data was used in the field of pedestrians trajectory prediction for advanced
driver-assistance systems and robot piloting systems; where it's mandatory to use real-world coordinates for navigation in real-world space.

**Comment by sunyuan789** [comment]
Thank you for your reply! I unstrand a lot but have another question. How to convert the positions from image coordinates to world coordinates? I see you use H matrix, but how to get it value? Thanks!

**Comment by Habiba-Amroune** [comment]
"H matrix" is the homography matrix provided with the dataset. It was used to project the world-coordinates positions (or trajectories) on the reference images (or videos) in the UCY dataset. u can find it here https://github.com/crowdbotp/OpenTraj/tree/master/datasets/UCY.

**Comment by sunyuan789** [comment]
You solved all my questions! I am grateful for you!
